set(CMAKE_SYSTEM_NAME Haiku)
set(CMAKE_SYSTEM_PROCESSOR aarch64)
set(CMAKE_SYSROOT /mnt/HaikuWork/build/summit-arm64/sysroot)
set(CROSS /mnt/HaikuWork/build/arm64/cross-tools-arm64/bin/aarch64-unknown-haiku-)
set(CMAKE_C_COMPILER ${CROSS}gcc)
set(CMAKE_CXX_COMPILER ${CROSS}g++)
set(CMAKE_AR ${CROSS}ar CACHE FILEPATH "")
set(CMAKE_RANLIB ${CROSS}ranlib CACHE FILEPATH "")
set(CMAKE_STRIP ${CROSS}strip CACHE FILEPATH "")
set(CMAKE_FIND_ROOT_PATH /mnt/HaikuWork/rpi4/summit-gl/deps /mnt/HaikuWork/build/summit-arm64/deps /mnt/HaikuWork/build/summit-arm64/sysroot/boot/system/develop /mnt/HaikuWork/build/summit-arm64/sysroot/boot/system)
set(CMAKE_PREFIX_PATH /mnt/HaikuWork/rpi4/summit-gl/deps /mnt/HaikuWork/build/summit-arm64/deps)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
set(CMAKE_C_FLAGS_INIT "-I/mnt/HaikuWork/rpi4/summit-gl/deps/include -I/mnt/HaikuWork/build/summit-arm64/deps/include")
set(CMAKE_CXX_FLAGS_INIT "-I/mnt/HaikuWork/rpi4/summit-gl/deps/include -I/mnt/HaikuWork/build/summit-arm64/deps/include")
set(CMAKE_EXE_LINKER_FLAGS_INIT "-L/mnt/HaikuWork/rpi4/summit-gl/deps/lib -Wl,-rpath-link,/mnt/HaikuWork/rpi4/summit-gl/deps/lib -L/mnt/HaikuWork/build/summit-arm64/deps/lib -Wl,-rpath-link,/mnt/HaikuWork/build/summit-arm64/deps/lib -Wl,-rpath-link,/mnt/HaikuWork/build/summit-arm64/sysroot/boot/system/lib")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "-L/mnt/HaikuWork/rpi4/summit-gl/deps/lib -Wl,-rpath-link,/mnt/HaikuWork/rpi4/summit-gl/deps/lib -L/mnt/HaikuWork/build/summit-arm64/deps/lib -Wl,-rpath-link,/mnt/HaikuWork/build/summit-arm64/deps/lib -Wl,-rpath-link,/mnt/HaikuWork/build/summit-arm64/sysroot/boot/system/lib")
set(ENV{PKG_CONFIG_LIBDIR} "/mnt/HaikuWork/rpi4/summit-gl/deps/lib/pkgconfig:/mnt/HaikuWork/build/summit-arm64/deps/lib/pkgconfig")
set(ENV{PKG_CONFIG_SYSROOT_DIR} "")
